#!/usr/bin/env python3
"""
Release script for th06.
Cleans build directory and creates a zip archive for distribution.
"""

import argparse
import shutil
import zipfile
from pathlib import Path

SCRIPTS_DIR = Path(__file__).parent
ROOT_DIR = SCRIPTS_DIR.parent
BUILD_DIR = ROOT_DIR / "build"


def clean_build():
    """Remove unnecessary files from build directory."""
    if not BUILD_DIR.exists():
        print("Build directory does not exist. Run build.py first.")
        return False

    # Patterns to remove
    patterns = ["*.obj", "*.pdb", "*.map", "*.res"]

    removed_count = 0
    for pattern in patterns:
        for file in BUILD_DIR.glob(pattern):
            file.unlink()
            removed_count += 1
            print(f"Removed: {file.name}")

    # Remove hidden files and autogenerated directory
    for item in BUILD_DIR.iterdir():
        if item.name.startswith(".") or item.name == "autogenerated":
            if item.is_dir():
                shutil.rmtree(item)
            else:
                item.unlink()
            removed_count += 1
            print(f"Removed: {item.name}")

    # Remove icon.ico (embedded in exe)
    icon_file = BUILD_DIR / "icon.ico"
    if icon_file.exists():
        icon_file.unlink()
        removed_count += 1
        print("Removed: icon.ico")

    print(f"\nCleaned {removed_count} files from build directory.")
    return True


def create_release(output_path=None, name="th06e-release"):
    """Create a zip archive of the build directory."""
    if not BUILD_DIR.exists():
        print("Build directory does not exist. Run build.py first.")
        return None

    if output_path is None:
        output_path = ROOT_DIR / f"{name}.zip"
    else:
        output_path = Path(output_path)

    # Files and directories to include
    include_items = [
        "th06e.exe",
        "th06.cfg",
        "th06c_CM.DAT",
        "th06c_ED.DAT",
        "th06c_IN.DAT",
        "th06c_MD.DAT",
        "th06c_ST.DAT",
        "th06c_TL.DAT",
        "BGM",
        "data",
    ]

    with zipfile.ZipFile(output_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for item_name in include_items:
            item_path = BUILD_DIR / item_name
            if not item_path.exists():
                print(f"Warning: {item_name} not found, skipping.")
                continue

            if item_path.is_file():
                zf.write(item_path, item_name)
                print(f"Added: {item_name}")
            elif item_path.is_dir():
                for file in item_path.rglob("*"):
                    if file.is_file():
                        arcname = str(file.relative_to(BUILD_DIR))
                        zf.write(file, arcname)
                        print(f"Added: {arcname}")

    print(f"\nCreated release archive: {output_path}")
    print(f"Size: {output_path.stat().st_size / 1024 / 1024:.2f} MB")
    return output_path


def main():
    parser = argparse.ArgumentParser(
        "th06-release", description="Clean build and create release archive"
    )
    parser.add_argument(
        "--no-clean",
        action="store_true",
        help="Skip cleaning build directory",
    )
    parser.add_argument(
        "--no-zip",
        action="store_true",
        help="Skip creating zip archive",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=str,
        default=None,
        help="Output path for zip archive",
    )
    parser.add_argument(
        "-n",
        "--name",
        type=str,
        default="th06e-release",
        help="Name of the release archive (default: th06e-release)",
    )
    args = parser.parse_args()

    if not args.no_clean:
        print("=== Cleaning build directory ===")
        if not clean_build():
            return 1

    if not args.no_zip:
        print("\n=== Creating release archive ===")
        if not create_release(args.output, args.name):
            return 1

    return 0


if __name__ == "__main__":
    exit(main())
